#!/usr/bin/env ruby
%w{optparse open-uri json}.each { |e| require e }

$options = {}
OptionParser.new do |p|
  p.on('-n', '--n-pieces INTEGER', Integer, 'Splits to n pieces.') { |v| $options[:n] = v }
end.parse!
n = $options[:n] || 1

ARGV.each do |e|
  system %Q(hadoop dfs -rmr #{e}/_logs #{e}/_SUCCESS)
  system %Q(mahout resplit -i #{e} -o #{e} -ns #{n})
  system %Q(hadoop dfs -rmr #{e})
end
