#!/bin/bash # called `tame-corpus`
[ ! -e ${MAHOUT_WORK}/corpus.csv ] && s3cmd get s3://${S3_BUCKET}-private/resources/rrc_pro_22110.csv ${MAHOUT_WORK}/corpus.csv
# [ ! -e ${MAHOUT_WORK}/corpus.csv ] && s3cmd get s3://${S3_BUCKET}-private/resources/rrc_ind_31771.csv ${MAHOUT_WORK}/corpus.csv

rm -rf ${MAHOUT_WORK}/comm-text-ext
prep-comm-text ${MAHOUT_WORK}/corpus.csv -d ${MAHOUT_WORK}/comm-text-ext
$HADOOP dfs -rmr ${MAHOUT_WORK}/comm-text-ext ${MAHOUT_WORK}/comm-text-seq
$HADOOP dfs -put ${MAHOUT_WORK}/comm-text-ext ${MAHOUT_WORK}/comm-text-ext
$MAHOUT seqdirectory -i ${MAHOUT_WORK}/comm-text-ext -o ${MAHOUT_WORK}/comm-text-seq -ow -chunk 5
