#!/bin/bash # called `tame-corpus`
[ ! -e ${MAHOUT_WORK}/corpus-l.csv ] && s3cmd get s3://${S3_BUCKET}-private/resources/rrc_pro_2285_labeled_typos.csv ${MAHOUT_WORK}/corpus-l.csv

rm -rf ${MAHOUT_WORK}/comm-text-ext
prep-comm-text ${MAHOUT_WORK}/corpus-l.csv -d ${MAHOUT_WORK}/comm-text-ext -i 4 -l 8 -f 1,3
$HADOOP dfs -rmr ${MAHOUT_WORK}/comm-text-ext ${MAHOUT_WORK}/comm-text-seq
$HADOOP dfs -put ${MAHOUT_WORK}/comm-text-ext/*.txt ${MAHOUT_WORK}/comm-text-ext
$MAHOUT seqdirectory -i ${MAHOUT_WORK}/comm-text-ext -o ${MAHOUT_WORK}/comm-text-seq -ow -chunk 5
