#!/bin/bash # called `tame-corpus`
case $1 in
  1) 
    [ ! -e ${MAHOUT_WORK}/corpus-1.csv ] && s3cmd get s3://${S3_BUCKET}-private/resources/rrc_pro_22110.csv ${MAHOUT_WORK}/corpus-1.csv;
    prep-comm-text ${MAHOUT_WORK}/corpus-1.csv -d ${MAHOUT_WORK}/comm-text-ext -i 3 -f 4,11
    ;;
  2)
    [ ! -e ${MAHOUT_WORK}/corpus-2.csv ] && s3cmd get s3://${S3_BUCKET}-private/resources/rrc_ind_31771.csv ${MAHOUT_WORK}/corpus-2.csv;
    prep-comm-text ${MAHOUT_WORK}/corpus-2.csv -d ${MAHOUT_WORK}/comm-text-ext -i 3 -f 4,11
    ;;
  3)
    [ ! -e ${MAHOUT_WORK}/corpus-l.csv ] && s3cmd get s3://${S3_BUCKET}-private/resources/rrc_pro_2285_labeled_typos.csv ${MAHOUT_WORK}/corpus-l.csv;
    prep-comm-text ${MAHOUT_WORK}/corpus-l.csv -d ${MAHOUT_WORK}/comm-text-ext -i 4 -l 8 -f 1,3
    ;;
esac

$HADOOP dfs -rmr ${MAHOUT_WORK}/comm-text-ext/corpus ${MAHOUT_WORK}/comm-text-seq
$HADOOP dfs -put ${MAHOUT_WORK}/comm-text-ext/corpus ${MAHOUT_WORK}/comm-text-ext/corpus
$HADOOP dfs -put ${MAHOUT_WORK}/comm-text-ext/corpus-priors ${MAHOUT_WORK}/comm-text-ext/corpus-priors
$MAHOUT seqdirectory -i ${MAHOUT_WORK}/comm-text-ext/corpus -o ${MAHOUT_WORK}/comm-text-seq -ow -chunk 5
